// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package io.grpc.examples.user;

public interface GetUserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetUserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
