// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package io.grpc.examples.user;

public interface GetUserListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetUserListRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 page = 1;</code>
   * @return The page.
   */
  int getPage();

  /**
   * <code>int32 size = 2;</code>
   * @return The size.
   */
  int getSize();
}
