// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package io.grpc.examples.user;

public interface GetUserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetUserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.User user = 1;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.User user = 1;</code>
   * @return The user.
   */
  io.grpc.examples.user.User getUser();
  /**
   * <code>.User user = 1;</code>
   */
  io.grpc.examples.user.UserOrBuilder getUserOrBuilder();
}
