// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package io.grpc.examples.user;

public final class UserServiceProto {
  private UserServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetUserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetUserListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetUserListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021UserService.proto\"\034\n\016GetUserRequest\022\n\n" +
      "\002id\030\001 \001(\005\"&\n\017GetUserResponse\022\023\n\004user\030\001 \001" +
      "(\0132\005.User\"0\n\022GetUserListRequest\022\014\n\004page\030" +
      "\001 \001(\005\022\014\n\004size\030\002 \001(\005\"\024\n\004User\022\014\n\004name\030\001 \001(" +
      "\t2\235\001\n\013UserService\022.\n\007GetUser\022\017.GetUserRe" +
      "quest\032\020.GetUserResponse\"\000\022-\n\013GetUserList" +
      "\022\023.GetUserListRequest\032\005.User\"\0000\001\022/\n\017GetU" +
      "serOneByOne\022\017.GetUserRequest\032\005.User\"\000(\0010" +
      "\001B+\n\025io.grpc.examples.userB\020UserServiceP" +
      "rotoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GetUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetUserRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_GetUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetUserResponse_descriptor,
        new java.lang.String[] { "User", });
    internal_static_GetUserListRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GetUserListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetUserListRequest_descriptor,
        new java.lang.String[] { "Page", "Size", });
    internal_static_User_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_descriptor,
        new java.lang.String[] { "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
